# ______  _   _   _____   _   _   ______  _   _   _   _____   _   _       ___   _____  
#|___  / | | | | /  _  \ | | | | |___  / | | | | | | /  ___| | | | |     /   | /  _  \ 
#   / /  | |_| | | | | | | | | |    / /  | |_| | | | | |     | |_| |    / /| | | | | | 
#  / /   |  _  | | | | | | | | |   / /   |  _  | | | | |     |  _  |   / / | | | | | | 
# / /__  | | | | | |_| | | |_| |  / /__  | | | | | | | |___  | | | |  / /  | | | |_| | 
#/_____| |_| |_| \_____/ \_____/ /_____| |_| |_| |_| \_____| |_| |_| /_/   |_| \_____/ 
#
#ZHICHAO出品必属精品


#聊天检索关键字；投票通过执行指令；投票通过世界广播；多数应大于少数数值；投票限定时间
vote_something:
    - 降雨;rain world rain;为世界带来了风调雨顺;6;60
    - 天晴;rain world sun;为世界带来了晴空万里;6;60
    - 日出;time set day;为世界带来了光明;6;60
    - 日落;time set night;为世界带来了黑夜;6;60
    - 重启服务器;stop;重启了服务器;10;60

vote_somebody:
    - 杀了;kill;6;60
    - 踢出;kick;6;60
    - ban了;ban;6;60
    - 解封;unban;6;60
    - 治疗;heal;6;60